
#
# Install a boardgame executable and set up the environment for it to run..
#
#

#
# Root of the board game distribution.
#
ARG DISTRIBUTION

FROM ubuntu:trusty
RUN whoami
RUN apt-get update

ARG DISTRIBUTION

ENV DIST $DISTRIBUTION
ENV HTTP_PORT 6587

#
# The Play server's pid (lock) file.
#
ENV PID_FILE

#
# Set up the base environment.
#
WORKDIR $DIST/script
ENV PATH $PATH:.
RUN echo `pwd` && ls && echo $PATH 

RUN ./install.sh

ENTRYPOINT ["run-server.sh"]
