
#
# Install a boardgame server and set up the environment for it to run.
#

#
# Parent image.
#
ARG BASE=azadbolour/jvm-node:1.0

FROM $BASE

# 
# This dockerfile will be placed by the corresponding build script 
# at the distribution package directory of the application. 
#
# The only files that can be used in a docker build are those that appear 
# below the current working directory of the build.
#
# That includes the dockerfile itself and any files to be copied into the image.
#
# Placing the dockerfile at the root of the distribution package allows the working 
# directory of docker build to be changed to the package root, so that the
# distribution can be copied into the image and installed there.
#

ENV HTTP_PORT 6587

#
# The Play server's pid (lock) file.
#
# ENV PID_FILE

#
# The application's distribution package is copied
# from the host machine to here.
#
ENV CONTAINER_PACKAGE_DIR=/opt/data/boardgame/package

#
# The distribution package includes the app's zipped play package,
# and a few specific startup scripts. Copy these into the container.
#
RUN mkdir -p $CONTAINER_PACKAGE_DIR/script 

#
# Copy the distribution zip file into the image.
#
# Note that build script that invokes this dockerfile
# changes directory to the root of the application's
# distribution package.
#
COPY *.zip $CONTAINER_PACKAGE_DIR

#
# Copy the scripts used to run the application into the image.
#
COPY script/* $CONTAINER_PACKAGE_DIR/script/

#
# Set up the base environment.
#
# Make sure to docker run with --workdir="" flag to start in the WORKDIR
# specified here.
#
WORKDIR $CONTAINER_PACKAGE_DIR/script
ENV PATH $PATH:.

RUN ./install.sh $CONTAINER_PACKAGE_DIR

ENTRYPOINT ["./run-server.sh"]
