
#
# Base of boardgame development.
#
ARG BASE=azadbolour/jvm-node:1.0

FROM BASE

#
# Set up the base environment.
#
ENV WORKSPACE /home/me/dev/boardgame
RUN mkdir -p $WORKSPACE \
  && echo `pwd`&& echo $PATH && whoami

WORKDIR $WORKSPACE

ENV PATH $PATH:.

#
# Install sbt from the official DEB package.
#
RUN wget --quiet https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb \
    && dpkg -i sbt-1.1.0.deb

#
# Clone the repository.
#
RUN cd .. && git clone https://github.com/azadbolour/boardgame 

#
# Install the web-ui dependencies.
#
RUN cd web-ui \
   && ./global-install.sh

#
# When started - pull the latest, package, and export the play application bundle.
# #
WORKDIR $WORKSPACE/scala-server
ENTRYPOINT ["./build-and-export-latest.sh"]

