
#
# Install a boardgame executable and set up the environment for it to run..
#

#
# Parent image.
#
ARG BASE=azadbolour/jvm-node:1.0

#
# Root of the board game distribution.
#
ARG INSTALL_ROOT

FROM $BASE

ARG INSTALL_ROOT

ENV INSTALL_DIR $INSTALL_ROOT
ENV HTTP_PORT 6587

#
# The Play server's pid (lock) file.
#
ENV PID_FILE

#
# Set up the base environment.
#
WORKDIR $DIST/script
ENV PATH $PATH:.

RUN ./install.sh $INSTALL_DIR

ENTRYPOINT ["run-server.sh"]
